### ISSUE TITLE
Als gebruiker wil zien bij de behandeling van een VL de kolommen 

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#113]
zoals opgenomen in de bijlage, zodat ik voldoende informatie heb om mijn werk uit te kunnen voeren 

*Clearification*

Same columns in the app #55. If more is needed, it will be clarified.

**Comment by JurjenBert** [comment]
Indien mogelijk graag rekening houden met #74

**Comment by SilviaAmAm** [comment]
Summary of what needs to be done:

- [ ] In the destruction list details page, the following coloumns should be visible (#113):

    Zaak identificatie
    Zaak omschrijving
    Looptijd (Zaak.Einddatum - Zaak.Startdatum)
    VCS (Zaak.Zaaktype.Selectielijstprocestype.Nummer)
    Relations to other zaken (yes/no) - issue #74

- [ ]  In the pop-up showing the zaak details, the related zaken should be shown (issue #74)

- [ ]  Depending on the role of the user, different data should be shown in the pop-up (issue #77)
