### ISSUE TITLE
Als RM wil ik een verkort vernietigingsproces kunnen doorlopen in geval van een doolopende machtiging,

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#114]
zodat er niet onnodig geklikt hoeft te worden. 

*Clearification*

![image](https://user-images.githubusercontent.com/96970/105357761-92075000-5bf5-11eb-9ca6-3db1606988cc.png)

The 2nd reviewer is optional for some zaaktypes. The zaaktypes that have an optional 2nd reviewer should be able to configured in the admin. For the other zaaktypes, a 2nd reviewer is mandatory.

If the 2nd reviewer is not filled, the 1st reviewer triggers already the destruction process after approval.

**Comment by SilviaAmAm** [comment]
- [ ] Change default so that the second reviewer is mandatory
- [ ] Admin: add page to configure the zaaktypen which have the second reviewer as optional

**Comment by joeribekker** [comment]
> To clarify: if there is at least one zaak of a zaaktype in the list that requires 2 reviewers, then the list should have two mandatory reviewers?

Yes.
