### ISSUE TITLE
Ik wil als ... een overzicht van rollen in de module met de personen in die rollen zitten,

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#116]
zodat ik kan laten zien wie wat mag. 
We gaan er vanuit dat datgene wat iemand aan zaakgegevens mag zien wordt bepaald door de OpenZaak autorisatie.

**Comment by joeribekker** [comment]
This was added to the documentation.

**Comment by joeribekker** [comment]
I think this is not about documentation in retrospect.

**Comment by joeribekker** [comment]
In overleg gesloten, admin biedt voldoende inzicht.
