### ISSUE TITLE
As a user i want to see all the action buttens in de demo environment,

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#158]
https://archiefvernietigingscomponent.test.maykin.opengem.nl/vernietigen/. 
This happens in the screens where a VL is opened. 
It is not so problematic, because after zooming out the buttons are visible and can be used. 

![knop bewaren niet zichtbaar](https://user-images.githubusercontent.com/40294293/109778950-ba776680-7c05-11eb-9aaa-aeceea60f2d9.JPG)
lijsten/

**Comment by joeribekker** [comment]
This was fixed I think, but not yet on the demo environment.

**Comment by SilviaAmAm** [comment]
Yes, this was fixed in this commit: https://github.com/maykinmedia/archiefvernietigingscomponent/commit/9ecbf5a0b9d5b11d49e16a19020cd0f7a0469635
