### ISSUE TITLE
As a record manager I want to see if and why archive data has been changed when selecting cases for a destruction list,

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#16]
so that I can take the adapted archive data into consideration when compiling lists. 
The addition of a column containing the reason for changing (see #17 ) might be enough, although cases with changed archive should stand out in the selection. 

During or after closing a zaak, a user can sometimes change archive data. The user will provide a reason for changing the data. The record manager should be able to see which cases deviate from what is configured in the corresponding zaaktype. The record manager should also be to see the reason for changing the data.

**Comment by sergei-maertens** [comment]
I take it this applies as well if the archive data has been changed by $externalSystem? I.e. any other application might be the source of the data change, and you still want to compare that then. Or is it sufficient if we only consider changes that are made from the RMA?

**Comment by joeribekker** [comment]
In overleg: Dit is prima als dit in de audit log terechtkomt via #240 en behoeft geen weegave in de abc.
