### ISSUE TITLE
Als proceseigenaar wil ik het controleren van de vernietigingslijst door een andere medewerker laten uitvoeren

### ISSUE THREAD

**Issue by RitaBerghuis** [maykinmedia/archiefvernietigingscomponent#234]
De verwachting is dat de proceseigenaar niet zelf de controle van de te vernietigen zaken zal uitvoeren, maar dit zal willen laten doen door een medewerker van zijn afdeling/proces.

**Comment by JurjenBert** [comment]
dit kan nu al.
