### ISSUE TITLE
Open Zaak aanpassingen een plek geven

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/archiefvernietigingscomponent#255]
Open Zaak aanpassingen moeten ergens op geplaatst worden met een duidelijke status van deze Open Zaak versie.

**Comment by joeribekker** [comment]
We'll create a fork named open-zaak-archiefbeheercomponent on the Maykin GitHub.

**Comment by SilviaAmAm** [comment]
https://github.com/maykinmedia/open-zaak/pull/2
