### ISSUE TITLE
Ik wil als record manager verschillende versies van een vernietigingslijst op kunnen slaan,

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#57]
zodat anonimisering plaats kan vinden.  Soms kan de beperkte informatie die in principe op een vernietigingslijst straat toch meer vertellen dan de bedoeling is. In dat geval wil ik gegevens uit de vernietigingslijst kunnen weglaten.
[aanvullen met voorbeelden; wordt deze gebruikt in de verklaring van vernietiging?]

[Thema uit conceptofferte: 2. Proces-verbaal/rapport genereren van vernietiging] 
[Thema uit conceptofferte: 5. verschillende versies van rapport mogelijk maken (anonimiseren)]

**Comment by joeribekker** [comment]
Deze kan al door aan te geven of er gevoelige informatie bij de zaken zit. Kan het ticket hiervoor niet direct vinden.
