### ISSUE TITLE
Ik wil als functioneel beheerder kunnen configureren welke kolommen getoond worden,

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#59]
op verschillende schermen in het proces en in een opgeslagen vernietigingslijst.  Zodat de betrokkenen in het vernietigingsproces de beschikking hebben over precies die informatie die ze nodig hebben. 
Denk aan gegevens als zaakomschrijving, selectielijstcategorie, vigerende selectielijst. Omdat de gegevens die een record manager enigszins variëren van gemeente tot gemeente, moet een beheerder aan kunnen geven wat relevant is voor de desbetreffende implementatie van de vernietigingsapp. 

[thema uit conceptofferte : 3. Additionele velden configureerbaar maken en toevoegen aan de vernietigingslijst]

**Comment by joeribekker** [comment]
De rollen en wat ze moeten kunnen zien is beschreven in #138 en #143 . Daarmee is dit ticket een stuk minder urgent.

**Comment by joeribekker** [comment]
Jurjen geeft aan sluiten omdat bovenstaande tickets hier genoeg mogelijkheden geven.
