### ISSUE TITLE
Ik wil als record manager zaakgegevens kunnen aanpassen en documenten kunnen toevoegen, verwijderen of vervangen,

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#60]
zodat ik de juiste informatie in een zaak kan opnemen wanneer dat niet het geval is.
Dit moet configurabel zijn, want dit is lang niet overal de werkwijze. In veel gemeentes zullen dit soort correcties vanuit de procesafhandeling plaatsvinden. 

[thema uit concept offerte 4. Aanpassen zaakgegevens / toevoegen document na bevriezen]

**Comment by RitaBerghuis** [comment]
We zijn tot de conclusie gekomen dat dit functionaliteit is van een zaakafhandelcomponent en niet primair van dit archiefbeheercomponent.
