### ISSUE TITLE
Als gebruiker in het vernietigingsproces wil ik via de mail notificaties kunnen ontvangen over de voortgang van het vernietigingsproces, 

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#61]
zodat ik in kan loggen op de applicatie wanneer er werk voor mij. Zo hoef ik niet proactief te controleren of er werk voor mij klaar staat. Het liefst wil ik zelf aan kunnen geven of ik notificaties ontvang, anders kan dit door een functioneel beheerder op het niveau van gebruikersrol worden ingesteld.  

[thema uit conceptofferte 6. Configuratie van notificaties toevoegen]

*Clearification*

Als er VLs aan mij zijn toegewezen/teruggewezen als reviewer, wil ik direct een mail ontvangen (er zit iets in je werkvoorraad).

**Comment by SilviaAmAm** [comment]
Split in issue https://github.com/maykinmedia/archiefvernietigingscomponent/issues/176
