### ISSUE TITLE
Als record manager wil ik dat na afronden van het vernietigingsproces een bevestiging van vernietiging verzonden worden naar in ieder geval de toezichthouder, 

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#62]
zodat ik kan voldoen aan wettelijke verplichtingen. 
-	Ik wil met de bevestiging van het afronden van het proces een verklaring van vernietiging meesturen  
[aanvullen: in welk bestandsformaat moet dit?] 
graag oppakken met #55 

[thema uit conceptofferte 6. Configuratie van notificaties toevoegen]

*Clearification*

An email should be sent to the "archivaris/toezichthouder" (existing role) with a list of all zaken that were actually destroyed. Technically, each DELETE call that returned HTTP 200).

Ofcourse, an email address should be part of the user/role.

**Comment by SilviaAmAm** [comment]
Steps:

- [ ] Create configurable template for the 'verklaring van vernietiging' (#55)
- [ ] Create function `generate_destruction_report()` that creates the 'verklaring van vernietiging' from the template and the zaken that were destroyed. This needs to check that the status of each `DestructionListItem` is `destroyed`.
- [ ] Modify https://github.com/maykinmedia/archiefvernietigingscomponent/blob/master/src/archiefvernietigingscomponent/destruction/tasks.py#L104 to use `generate_destruction_report()` and to send it to the process eigenaar.
