### ISSUE TITLE
Als functioneel beheerder wil ik in kunnen stellen welke tekst wordt meegestuurd in mails, 

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#63]
zodat de ontvanger weet waarom hij wordt gemaild: wordt er bijvoorbeeld een verklaring van vernietiging verstuurd? Of wordt een proces eigenaar gevraagd om actie. 

[thema uit conceptofferte 6. Configuratie van notificaties toevoegen]

*Clearification*

Vanuit proces geldt dit voor alle mailtjes.

We hebben goede defaults nodig.

**Comment by SilviaAmAm** [comment]
Split in issue https://github.com/maykinmedia/archiefvernietigingscomponent/issues/176

**Comment by JurjenBert** [comment]
Notificatie 1 
Wordt verstuurd wanneer: 
-vernietigingslijst moet worden bekeken door proces eigenaar, (proces eigenaar ontvangt notificatie) 
- vernietigingslijst moet worden bekeken door archivaris  (archivaris ontvangt notificatie),
- vernietigingslijst komt terug bij record manager (na afkeuren door proces eigenaar of archivaris) (record manager ontvangt notificatie)

onderwerp :  Uw accordering van een vernietigingslijst wordt gevraagd
inhoud: Beste [naam gebruiker],   Uw accordering van een vernietigingslijst wordt   gevraagd. U kunt onderstaande link gebruiken om de lijst te bekijken en te controleren of de zaken op de lijst daadwerkelijk vernietigd kunnen worden. Ga alstublieft hierheen: [ https://etcetera   ]

Notificatie 2
Wordt verstuurd wanneer: er is vernietigd (archivaris ontvangt notificatie)
onderwerp: Zaken op vernietigingslijst vernietigd
inhoud: Geachte gemeentearchivaris [naam ]
Ingevolge het bepaalde in artikel 8 van het Archiefbesluit 1995, zoals gemandateerd aan de hoofden van de organisatieonderdelen in de mandaatregeling 2020 Gemeente [gemeentenaam] vastgesteld op datum x [ik doe navraag of deze herleidbaar is] , verklaar ik hierbij dat de vernietiging zoals omschreven in [naam vernietigingslijst] is uitgevoerd. De zaken zijn onherstelbaar vernietigd. U kunt de vernietigingslijst in PDF formaat via deze link downloaden: [ https://etcetera ]

Hoogachtend,

Hoofd Organisatieonderdeel [ik doe navraag of deze herleidbaar is]

**Comment by JurjenBert** [comment]
@SilviaAmAm Here is a default value for a notifcation in case the proces owner or archivist  is not not OK with de vernietigignslijst and proposes changes. 
 
onderwerp : Voorstel voor wijziging van uw vernietigingslijst
inhoud: Beste [naam gebruiker], er is een voorstel tot aanpassing van uw vernietigingslijst [naam vernietigingslijst]. U kunt onderstaande link gebruiken om de lijst en de voorgestelde wijziging te bekijken en af te handelen. Ga alstublieft hierheen: [ https://etcetera ]
