### ISSUE TITLE
Als functioneel beheerder wil ik weten waarom en in welke situaties zonder reviewproces vernietigd mag worden, 

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#65]
zodat ik relevante user stories op kan stellen. 
Duidelijk is alk wel dat deze situatie zeker niet voor alle implementaties gewenst zijn is, dus moet -in geval van opgeleverde functionaliteit – deze minimaal uit te zetten zijn.

Maw: meer input nodig. 

[thema uit concept offerte: 7. Vernietigen zonder (review)proces mogelijk maken]

**Comment by joeribekker** [comment]
Decided this was a non-issue since you always need at least 1 reviewer.
