### ISSUE TITLE
Ik wil als record manager het proces van vernietiging kunnen annuleren, 

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#71]
zodat ik in voorkomende gevalle opnieuw kan beginnen.  De zaken die voorkwamen op deze lijst zijn weer beschikbaar voor opname op nieuwe lijsten. 

[overig - proces]

*Clearification*

Record manager creates a destruction list, and wants to cancel/delete the destruction list (JUST THE LIST). THis will cause the zaken on that list to be available again to be put onto new destroying lists. This should be possible at all times (until actual destruction ofcourse).

The cancellation should trigger a notification to the reviewer (if any).

**Comment by SilviaAmAm** [comment]
- [ ] Modify current behaviour. Now the record manager who created the list can only modify/abort it when they are assigned to the list.
- [ ] Add a confirmation box about aborting the list.
- [ ] Make sure that an already aborted list doesn't have the "aborted button". 
- [ ] If a request to abort an already aborted list is made, make sure errors are handled gracefully. 

What should happen if:
- The record manager creates a list, the first assignee reviews it. Should now the record manager be allowed to update the list?
