### ISSUE TITLE
Ik wil als record manager kunnen zien of een zaak op een vernietigingslijst een relatie heeft met een andere zaak

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#74]
zodat ik hier indien nodig actie op kan ondernemen.  
Er is hier meer info nodig -  Wat gebeurt er als er vernietigd wordt in de context van relaties? 

Het gaat hier dus om de aanwezigheid van een relatie. Heeft dit functionele consequenties ? 
[overig - relaties]

**Comment by JurjenBert** [comment]
iom Rita op prio High gezet

**Comment by joeribekker** [comment]
From Jurjen:
Maybe show in columns (see #113 )

**Comment by joeribekker** [comment]
Final columns are described in #143, including relations.

**Comment by SilviaAmAm** [comment]
After discussion:
No pop-up is needed because there will be a link redirecting to the Zaakafhandelcomponent to see the zaak details.
So the 'relaties' column should only say Yes/No
