### ISSUE TITLE
Afhankelijk van mijn rol wil ik informatie over zaak zien adhv de autorisatie die ik heb op een zaaktype, 

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#76]
zodat ik alleen de gegevens zie, die ik mag zien. 

Dit werkt grotendeels al zo (of helemaal?) maar het is me niet helemaal duidelijk hoe dit nu werkt.
Klopt het 
- dat wanneer een zaak wordt aangeklikt in een VL, er een sjabloon met een aantal gegevens worden geopend (besluiten, resultaat, documenten).  
- en dat er deze gegevens worden gevuld of niet gevuld adhv open zaak autorisatie? 

[overig - autorisaties]

**Comment by joeribekker** [comment]
No longer needed because in #77 we refer to a Zaak-app that should handle authorizations.
