### ISSUE TITLE
Als gebruiker in het vernietigingsproces wil ik dat relevante informatie wordt getoond wanneer ik een zaak aanklik op een VL,

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#77]
*Warning: Ticket changed scope*

- [x] There should be a link to a Zaak-application (Open Zaak or (g)ZAC).
- [x] This link should be configurable using 3 variables: zaak.uuid, zaak.identificatie, zaak.bronorganisatie.
- [ ] The popup can be removed

*Old version*

zodat ik de informatie zie die ik nodig heb voor mijn werk. Nu worden besluiten, resultaat en documenten getond. 
Het scherm moet vervolgens gevuld worden adhv mijn openzaak autorisatie. 

Eerste stap zou zijn welke zaakdetails een record manager, proceseigenaar en toezichthouder maximaal moeten kunnen zien, 
Denk aan bijvoorbeeld documenttitel? 

[overig - autorisaties]

**Comment by JurjenBert** [comment]
[
![zaakdetails](https://user-images.githubusercontent.com/40294293/99679912-c71fe680-2a7c-11eb-8935-ed3efdca71c0.PNG)
](url)

**Comment by SilviaAmAm** [comment]
The pop-up was kept, because it is needed to review whether a zaak needs to be changed, removed or kept in the list.
