### ISSUE TITLE
Als proces eigenaar wil ik bij het motiveren van een voorstel tot aanpassing van de VL gebruik kunnen maken van standaard redenen

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#82]
zodat ik minder hoef te typen. 

Denk bijvoorbeeld aan een pull down met gangbare redenen (zoals hotspot, precedentwerking, relevant voor bedrijfsvoering… ) 

[overig - usability]

*Clearification*

* As reviewer pick (default) reasons from droplist
* In the admin manage list of top reasons.
* The above x 2 for both reviewers (they have different reasons).

@Mirjam will create some default reasons.

**Comment by JurjenBert** [comment]
options for the pull down (with thanks to Mirjam) apart from the possibiltiy of adding your own reasing  

-	Zaken die bij een vastgestelde Hotspot behoren.
-	Zaken met een uniek karakter.
-	Bijzondere gebeurtenissen.
-	Beeldbepalende, karakteristieke, bijzondere objecten.
-	Samenvattingen van gegevens.
-	Belangrijke burgers en functionarissen.
-	Bescheiden die vervangen wat door een calamiteit verloren is gegaan.
-	Precedenten: individuele zaken die leiden tot algemene regels.
-	Bescheiden waarbij de vernietiging de logische samenhang zou verstoren.
-	Zaken die van belang zijn voor de huidige bedrijfsvoering/nog andere lopende zaken.

**Comment by JurjenBert** [comment]
@SilviaAmAm I checked with @renzoramaekers and mirjam: they agree that only 1 list is fine.  So all reviewers have the same standard options. 
Mirjam mentioned that she would like the option "Zaken die van belang zijn voor de huidige bedrijfsvoering/nog andere lopende zaken." to be shown as first as a default. 

I understand from the user story  that the list of reasons van be configured by an admin. Is that correct?

**Comment by SilviaAmAm** [comment]
Okay, thank you for the clarification! 

Yes indeed, the reasons will be configurable from the admin!
