### ISSUE TITLE
Als functioneel beheerder wil ik antwoord op de vraag hoe we om kunnen gaan met flexibiliteit in de procesgang,

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#83]
Zodat ik weet hoe we hier mee om kunnen gaan.  
Hieronder enkele voorbeelden waarin wordt afgeweken van het standaard proces:

1. Bijv een situatie waarin de archivaris/toezichthouder kan nog zaken uitzonderen. 

2. Igv in geval van een doorlopende machtiging mag het akkoord door toezichthouder worden overgeslagen

3. In het kan voorkomen sommige gevalle gevallen wil dat de record manager je een uitrspraak wil van de functionaris gegevensbescherming (FG) over het al dan niet opnemen van een een zaak die op de VL voorkomt, voordat de lijst weer naar de proceseigenaar gaat. Bijvoorbeeld: de pProceseigenaar wil de archiefactiedatum vooruit schuiven, maar de record manager is het hier niet mee eens, en zoekt uitsluitsel bij verlengen, daarna zet  record manager de de FG. suggestie door aan FG. Fg kan De onderbouwing van de FG kan dan mee naar de proceseigenaar dan voor odnerbouweing zorgen waarom een suggestie bijv. niet is overgenomen (om te voorkomen dat de een vl VL heen en weer blijft gaan tussen record manager en proceseigenaar) 

4. Het kan voorkomen (?) dat het niet gewenst is dat het akkoord van de toezichthouder niet de trigger is die leidt tot vernietiging 
	
[overig - proces]

*Clearification*

1. Might be already in.
2. Is detailed in #114 
3. TODO?
4. Is the same as #114 (doublecheck).

**Comment by SilviaAmAm** [comment]
After discussion:
During the review process, it can happen that the process owner requests changes, but the record manager disagrees. In this case, it needs to be possible to request  a review from a different reviewer. After this extra review step, then the process owner can review again.

The extra reviewer should have a new role: GDPR Officer (They can also see sensitive data)

**Comment by joeribekker** [comment]
Op dit moment kan je "willekeurige" personen binnen deze applicatie een bepaalde rol toebedelen (archivaris, processeigenaar). Deze labels zijn ook al aan te passen met een andere naam. Dit tackelt deels? punt 3.

@SilviaAmAm is this correct?

**Comment by joeribekker** [comment]
In de kerngroep is besloten dat dit voor nu voldoende is. Daarmee verdwijnt dit story van de backlog.
