### ISSUE TITLE
Ik wil als functioneel beheerder duidelijkheid over het opslaan van de verklaring van vernietiging (en wellicht een afschrift) bij een zaak

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#86]
zodat ik hiervoor relevante user stories kan opstellen.
Hoe zou dit in zijn werk zou moeten gaan?  Bijvoorbeeld na vernietiging een mail genereren naar medewerker die met de bijlage(n) een zaak aanmaakt? Of die mail afleveren op een process engine en automatisch een zaak aanmaken? Of wordt het proces van het doorlopen van de archiefbeheercomponent een zaak?

[Overig – langere termijn oplossingsrichting verkennen]

**Comment by RitaBerghuis** [comment]
Na afstemmingsoverleg (op 7 mei) met gemeenten Utrecht, Hoorn, Rotterdam, VNG en Delft is hieruit gekomen dat het meest voor de hand liggende scenario is, dat het AVC zelf een zaak aanmaakt in Open Zaak. De uitvoering van het vernietigingsproces wordt dus zaakgericht afgehandeld. Dus #155 kan uitgevoerd worden in de volgende iteratie. Omdat niet alle gemeenten hetzelfde zullen werken, is het wellicht een idee om dit configurabel te maken? Dus dat een gemeente ervoor kan kiezen om de vernietigingszaak direct in Open Zaak aan te alten maken of niet.

**Comment by joeribekker** [comment]
Deze heeft geleid tot #155 en kan gesloten worden.
