### ISSUE TITLE
Als functioneel beheerder wil ik dat de naam van de archiefbeheercomponent wordt vastgesteld, 

### ISSUE THREAD

**Issue by JurjenBert** [maykinmedia/archiefvernietigingscomponent#88]
zodat we eenduidig kunnen communiceren. 
Nu worden iig de termen archiefbeheermodule, archiefbeheercomponent en vernietigingsapp door / naast elkaar gebruikt.  

--
Decided on "archiefvernietigingscomponent"

We need to rename everything :)

- [x] Rename in documentation
- [x] Rename Github repo
- [x] Rename Docker repo
- [x] Rename ReadTheDocs
- [x] Rename domain / deploy tooling

**Comment by RitaBerghuis** [comment]
Het lijkt mij goed om hier in overleg met alle deelnemers een klap op te geven, want ik merk dat Archiefbeheercomponent niet altijd bij iedereen duidelijk is.

**Comment by RitaBerghuis** [comment]
De naam van het component moet duidelijk maken wat het doet. En dat is het vernietigen van zaken. Dus in ieder geval iets met vernietigen.
Vernietiging alleen staat zo dreigend en waarschijnlijk niet voor iedereen direct duidelijk dat het om vernietigen van zaken gaat.
Daarom zoiets als Zaakvernietiging?
Wat denken jullie @renzoramaekers en @JurjenBert?

**Comment by renzoramaekers** [comment]
Een passende naam als het alleen een vernietigings app blijft met de afkorting ZVC (zaak vernietigings component)! Wat als de app uitgebreid wordt met overbrengingsfunctionaliteit?

**Comment by RitaBerghuis** [comment]
Dan wordt het ZVO (Zaakvernietiging en Overbrenging :-) 
Of er ontstaan 2 componenten (ZVC en ZOC) binnen 1 informatiebeheer app?

**Comment by JurjenBert** [comment]
ik heb geen voorkeur. Als recordmanagers er zich maar in kunnen vinden (& en dat lijkt me wel in bovenstaande lettercombinaties?)  
(al bedacht ik me wel dat ArchiefBeheerComponent ook een mooie letter combi oplevert: ABC :) )

**Comment by joeribekker** [comment]
idea: make a mentimeter on thursday with options and vote for it.

**Comment by joeribekker** [comment]
Conclusie uit overleg: "Archiefvernietingscomponent"
